global:
  edition: ce
  ingress:
    configureCertmanager: false
    class: "nginx"
  hosts:
    domain: 192.168.99.100.nip.io
    externalIP: 192.168.99.100

  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: NodePort
      nodePort: 32022
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1